export const HTTP_STATUS_CODES = {
  SUCCESS_OK: 200,
  SUCCESS_CREATED: 201,
  SUCCESS_ACCEPTED: 202,
  SUCCESS_NO_CONTENT: 204,

  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  NOT_MODIFIED: 304,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const DB_CONSTANTS = {
  CHAT_BUDDY_SCHEMA: "chat-buddy",
  TABLES: {
    USERS: "tb_users",
    SESSIONS: "tb_sessions",
    MESSAGES: "tb_messages",
    REFRESH_TOKENS: "tb_refresh_tokens",
  },
} as const;

export const URLS = {
  BASE_URL: "SOME_URL",
  WS_URL: "SOME_WS_URL",
  MESSAGE_QUEUE_URL: "SOME_MESSAGE_QUEUE_URL",
} as const;
